<?php
require_once __DIR__ . '/../includes/header.php';
require_once __DIR__ . '/../includes/reconciliacion_efectivo_helpers.php';
checkAdmin(); reconciliacionAsegurarEsquema($pdo);
$calculo = reconciliacionCalculoActual($pdo); $custodios = reconciliacionCustodios($pdo, false); $activos = array_values(array_filter($custodios, static fn($c)=>(int)$c['activo']===1)); $historico = reconciliacionHistorico($pdo); $corte = isset($_GET['corte']) ? reconciliacionCorte($pdo, (int)$_GET['corte']) : null;
?>
<div class="d-flex justify-content-between align-items-start flex-wrap gap-3 mb-4"><div><p class="text-muted small mb-1">Copias y respaldos · Administración</p><h1 class="h4 mb-1"><i class="bi bi-cash-stack text-primary"></i> Reconciliación de Efectivo</h1><p class="text-muted mb-0">Calcula el efectivo esperado y lo compara contra los sitios de custodia registrados.</p></div><a class="btn btn-success" href="../actions/export_reconciliacion_efectivo_excel.php"><i class="bi bi-file-earmark-excel"></i> Exportar histórico</a></div>
<?php if(isset($_GET['guardado'])): ?><div class="alert alert-success">Corte archivado correctamente.</div><?php endif; ?>
<div class="row g-3 mb-4">
 <div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted small">Saldo general natillera</div><div class="h3 mb-0"><?php echo reconciliacionFormatoMoneda($calculo['saldo_general']); ?></div></div></div></div>
 <div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted small">- Cartera vigente dinámica</div><div class="h3 mb-0"><?php echo reconciliacionFormatoMoneda($calculo['cartera_vigente']); ?></div></div></div></div>
 <div class="col-md-4"><div class="card h-100"><div class="card-body"><div class="text-muted small">= Efectivo esperado</div><div class="h3 mb-0 text-primary"><?php echo reconciliacionFormatoMoneda($calculo['efectivo_esperado']); ?></div></div></div></div>
</div>
<div class="card mb-4"><div class="card-header"><i class="bi bi-clipboard-check"></i><span>Nuevo corte</span></div><div class="card-body"><form method="post" action="../actions/reconciliacion_corte_save.php"><div class="row g-3"><div class="col-md-3"><label class="form-label">Fecha del corte</label><input class="form-control" type="date" name="fecha_corte" value="<?php echo date('Y-m-d'); ?>" required></div><div class="col-md-9"><label class="form-label">Observaciones generales</label><input class="form-control" name="observaciones" placeholder="Notas del corte"></div></div><div class="table-responsive mt-3"><table class="table align-middle"><thead><tr><th>Sitio/persona</th><th>Tipo</th><th class="text-end">Valor real</th><th>Observaciones</th></tr></thead><tbody><?php foreach($activos as $c): ?><tr><td class="fw-semibold"><?php echo clean($c['nombre']); ?></td><td><span class="badge bg-light text-dark"><?php echo clean($c['tipo']); ?></span></td><td><input class="form-control text-end" type="number" step="0.01" min="0" name="valor[<?php echo (int)$c['id']; ?>]" value="0"></td><td><input class="form-control" name="observacion_item[<?php echo (int)$c['id']; ?>]" placeholder="Opcional"></td></tr><?php endforeach; ?></tbody></table></div><button class="btn btn-primary"><i class="bi bi-save"></i> Guardar corte histórico</button></form></div></div>
<div class="row g-4"><div class="col-lg-5"><div class="card"><div class="card-header"><i class="bi bi-geo-alt"></i><span>Sitios de custodia editables</span></div><div class="card-body"><form class="row g-2 mb-3" method="post" action="../actions/reconciliacion_custodio_save.php"><div class="col-5"><input class="form-control" name="nombre" placeholder="Nombre" required></div><div class="col-4"><select class="form-select" name="tipo"><option value="persona">Persona</option><option value="banco">Banco</option><option value="efectivo">Efectivo</option><option value="nequi">Nequi</option><option value="otro">Otro</option></select></div><div class="col-3"><button class="btn btn-outline-primary w-100">Agregar</button></div></form><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Nombre</th><th>Tipo</th><th>Activo</th></tr></thead><tbody><?php foreach($custodios as $c): ?><tr><td><?php echo clean($c['nombre']); ?></td><td><?php echo clean($c['tipo']); ?></td><td><?php echo (int)$c['activo']===1?'Sí':'No'; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div><div class="col-lg-7"><div class="card"><div class="card-header"><i class="bi bi-clock-history"></i><span>Histórico de cortes</span></div><div class="card-body"><div class="table-responsive"><table class="table table-striped align-middle"><thead><tr><th>Fecha</th><th class="text-end">Esperado</th><th class="text-end">Ubicado</th><th class="text-end">Diferencia</th><th></th></tr></thead><tbody><?php foreach($historico as $h): $dif=(float)$h['diferencia']; ?><tr><td><?php echo clean($h['fecha_corte']); ?></td><td class="text-end"><?php echo reconciliacionFormatoMoneda($h['efectivo_esperado']); ?></td><td class="text-end"><?php echo reconciliacionFormatoMoneda($h['total_ubicado']); ?></td><td class="text-end fw-bold <?php echo $dif>0?'text-danger':($dif<0?'text-success':'text-muted'); ?>"><?php echo reconciliacionFormatoMoneda($dif); ?></td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="?corte=<?php echo (int)$h['id']; ?>">Ver</a> <a class="btn btn-sm btn-outline-success" href="../actions/export_reconciliacion_efectivo_excel.php?corte=<?php echo (int)$h['id']; ?>">Excel</a></td></tr><?php endforeach; ?></tbody></table></div></div></div></div></div>
<?php if($corte): ?><div class="card mt-4"><div class="card-header"><i class="bi bi-search"></i><span>Detalle corte #<?php echo (int)$corte['id']; ?></span></div><div class="card-body"><div class="row g-3 mb-3"><div class="col-md-3">Esperado: <strong><?php echo reconciliacionFormatoMoneda($corte['efectivo_esperado']); ?></strong></div><div class="col-md-3">Ubicado: <strong><?php echo reconciliacionFormatoMoneda($corte['total_ubicado']); ?></strong></div><div class="col-md-3">Diferencia: <strong class="<?php echo $corte['diferencia']>0?'text-danger':($corte['diferencia']<0?'text-success':''); ?>"><?php echo reconciliacionFormatoMoneda($corte['diferencia']); ?></strong></div></div><h6>Sitios</h6><ul><?php foreach($corte['items'] as $i): ?><li><?php echo clean($i['nombre_custodio']); ?>: <?php echo reconciliacionFormatoMoneda($i['valor']); ?></li><?php endforeach; ?></ul><h6>Cartera vigente detallada</h6><ul><?php foreach($corte['cartera'] as $p): ?><li>#<?php echo (int)$p['id_prestamo']; ?> <?php echo clean($p['deudor']); ?> — <?php echo reconciliacionFormatoMoneda($p['saldo_capital_actual']); ?></li><?php endforeach; ?></ul></div></div><?php endif; ?>
<?php require_once __DIR__ . '/../includes/footer.php'; ?>
