<?php
use Dompdf\Dompdf; use Dompdf\Options;
require_once __DIR__ . '/../config/db.php'; require_once __DIR__ . '/../includes/auth.php'; require_once __DIR__ . '/../includes/functions.php'; require_once __DIR__ . '/../includes/libro_diario_helpers.php'; checkAdmin();
$autoload = __DIR__ . '/../vendor/autoload.php'; if (file_exists($autoload)) { require_once $autoload; }
if (!class_exists(Dompdf::class)) { die('DOMPDF no está disponible.'); }
$appName = trim(getConfiguracionGeneral($pdo)['nombre_sistema'] ?? '') ?: 'Natillera';
$idSocio = isset($_GET['socio_detalle']) ? (int) $_GET['socio_detalle'] : null; $socio=null; if($idSocio){$st=$pdo->prepare('SELECT * FROM socios WHERE id_socio=:id');$st->execute([':id'=>$idSocio]);$socio=$st->fetch();}
$filtros=['desde'=>$_GET['desde']??'', 'hasta'=>$_GET['hasta']??'', 'socio'=>$_GET['socio']??'', 'actividad'=>$_GET['actividad']??'', 'medio'=>$_GET['medio']??'', 'prestamo'=>$_GET['prestamo']??'', 'neutrales'=>isset($_GET['neutrales'])?'1':''];
$rows=libroDiarioObtenerMovimientos($pdo,$filtros,$idSocio?:null); $totales=libroDiarioAplicarSaldo($rows,(bool)$idSocio); ob_start(); ?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;font-size:10px}h1{font-size:18px}.muted{color:#666}.danger{color:#b91c1c;font-weight:bold}table{width:100%;border-collapse:collapse}th,td{border:1px solid #ddd;padding:4px}th{background:#f1f5f9}.right{text-align:right}tfoot th{background:#f8fafc}</style></head><body>
<h1><?php echo htmlspecialchars($idSocio ? 'Auxiliar individual' : 'Libro diario / Auxiliar de movimientos'); ?></h1><p><strong><?php echo htmlspecialchars($appName); ?></strong><?php echo $socio ? ' — Socio: '.htmlspecialchars($socio['nombre_completo']) : ''; ?><br><span class="muted">Rango: <?php echo htmlspecialchars(($filtros['desde'] ?: 'inicio') . ' a ' . ($filtros['hasta'] ?: 'fin')); ?></span></p>
<table><thead><tr><th>Fecha</th><?php if(!$idSocio):?><th>Socio / tercero</th><?php endif;?><th>Concepto</th><th>Préstamo</th><th>Medio</th><th>Ingreso</th><th>Egreso</th><th>Neutral</th><th>Saldo</th><th>Liq.</th><th>Usuario</th><th>Observaciones</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?php echo htmlspecialchars($r['fecha']);?></td><?php if(!$idSocio):?><td><?php echo $r['id_socio']?htmlspecialchars($r['nombre_completo']):'<span class="danger">SIN SOCIO</span>';?></td><?php endif;?><td><?php echo htmlspecialchars(($r['nombre_actividad']??'').(!empty($r['es_aval'])?' (aval)':''));?></td><td><?php echo $r['id_prestamo']?'#'.(int)$r['id_prestamo']:'';?></td><td><?php echo htmlspecialchars($r['medio_pago_nombre']?:$r['medio_consignacion']);?></td><td class="right"><?php echo ((int)$r['es_ingreso']===1&&empty($r['es_aval']))?libroDiarioMoney($r['valor_abs']):'';?></td><td class="right"><?php echo ((int)$r['es_egreso']===1&&empty($r['es_aval']))?libroDiarioMoney($r['valor_abs']):'';?></td><td class="right"><?php echo ((int)$r['es_ingreso']!==1&&(int)$r['es_egreso']!==1)?libroDiarioMoney($r['valor_abs']):'';?></td><td class="right"><?php echo libroDiarioMoney($r['saldo_acumulado']);?></td><td><?php echo $r['id_liquidacion']?'#'.(int)$r['id_liquidacion']:'';?></td><td><?php echo htmlspecialchars($r['usuario_registro']);?></td><td><?php echo htmlspecialchars($r['observaciones']);?></td></tr><?php endforeach;?></tbody><tfoot><tr><th colspan="<?php echo $idSocio?5:6;?>">Totales</th><th class="right"><?php echo libroDiarioMoney($totales['ingresos']);?></th><th class="right"><?php echo libroDiarioMoney($totales['egresos']);?></th><th class="right"><?php echo libroDiarioMoney($totales['neutral']);?></th><th class="right"><?php echo libroDiarioMoney($totales['saldo_final']);?></th><th colspan="3"></th></tr></tfoot></table></body></html>
<?php $html=ob_get_clean(); $dompdf=new Dompdf(new Options(['isRemoteEnabled'=>true])); $dompdf->loadHtml($html,'UTF-8'); $dompdf->setPaper('A4','landscape'); $dompdf->render(); $dompdf->stream(($idSocio?'auxiliar_socio_'.$idSocio:'libro_diario').'.pdf',['Attachment'=>true]);
